### ISSUE TITLE
Pages get stuck loading

### ISSUE THREAD

**Issue by bjoberg** [bjoberg/social-pulse#1]
The following pages get stuck loading when you refresh or navigate directly to them:
- /dashboard
- /account/profile
- /login
- /signup

**Note**: The application stills works if you navigate away from the page that is stuck. Just stop the refresh and everything will be fine.

**Comment by stefaluc** [comment]
Problem was fixed in commits [5e60a42](https://github.com/bjoberg/social-pulse/commit/5e60a4297aeb005dc9db2a96e9b3a46f388c3b49) and [9608c22](https://github.com/bjoberg/social-pulse/commit/9608c22ecbed09d6c1a5245f06d9b42aa8e9dcb1)
