### ISSUE TITLE
Incorrect language in Privacy screen

### ISSUE THREAD

**Issue by amoore8765** [bjoberg/social-pulse#5]
Summary: Incorrect language displayed on Privacy page
Description: Upon opening the Privacy page by selecting the link on the main page, text appears in a language other than that used on the rest of the website. All pages of the website should display in the language that is set through the user’s browser, or just be a single consistently chosen language throughout the whole website.
Severity – Trivial: This should be an easy fix, and is low priority due to limited impact on correctness of the deliverable, but the page may contain important and valuable information so it must be readable to the user.

**Comment by amoore8765** [comment]
Low Priority Issue

**Comment by ivanpereda95** [comment]
This page also had Latin placeholder text. Privacy now has content.
