### ISSUE TITLE
Incorrect language Security Screen

### ISSUE THREAD

**Issue by amoore8765** [bjoberg/social-pulse#6]
Summary: Incorrect language displayed on Security page
Description: Upon opening the Security page by selecting the link on the main page, text appears in a language other than that used on the rest of the website. All pages of the website should display in the language that is set through the user’s browser, or just be a single consistently chosen language throughout the whole website.
Severity – Trivial: This should be an easy fix, and is low priority due to limited impact on correctness of the deliverable, but the page may contain important and valuable information so it must be readable to the user.

**Comment by ivanpereda95** [comment]
Text was a placeholder that was in Latin and browser properly suggested a translation. This page was updated and changed, removed the Latin placeholder text.
