### ISSUE TITLE
Incorrect About Page Language

### ISSUE THREAD

**Issue by amoore8765** [bjoberg/social-pulse#7]
Summary: Incorrect language displayed on About Page
Description: Upon opening the About Page by selecting the link on the main page, text appears in a language other than that used on the rest of the website. All pages of the website should display in the language that is set through the user’s browser, or just be a single consistently chosen language throughout the whole website.
Severity – Trivial: This should be an easy fix, and is low priority due to limited impact on correctness of the deliverable, but the page may contain important and valuable information so it must be readable to the user.

**Comment by ivanpereda95** [comment]
Page language was not incorrect, as mentioned in another ticket: we had placeholder text. Should all be good now as content has been filled.
