### ISSUE TITLE
Docs link is broken

### ISSUE THREAD

**Issue by amoore8765** [bjoberg/social-pulse#8]
Summary: Link to Docs page broken
Description: When selecting the link on either the bottom or top banner of the website labeled “Docs”, the user is not directed to a different page. 
Severity – Medium: This constitutes an entirely missing page from the website, and as a result it is rather important to guarantee that there are no broken pages on the website, but this should be a rather easy change.

**Comment by ivanpereda95** [comment]
Docs was ultimately removed.
