### ISSUE TITLE
Contact Page Is Broken

### ISSUE THREAD

**Issue by amoore8765** [bjoberg/social-pulse#9]
Summary: Contact Page is broken
Description: When navigating to the Contact page, the user sees an empty form, prompting them to enter information. Regardless of what a user enters, hitting the submit button on the form has no effect. This page seems to be broken, and its assumed purpose of displaying contact information for a user to get customer service or comment suggestions email is unfulfilled. This should be fixed or removed if contact information is deemed unnecessary.
Severity – Medium: Having a broken page is confusing and should not exist in a final product, however this shouldn’t be a difficult fix.

**Comment by ivanpereda95** [comment]
Contact page fixed, should have proper functionality now.
